import Link from "next/link";

const features = [
  { number: "01", title: "Ask better questions", copy: "Turn a blank page into a thoughtful conversation with a form that feels effortless to complete.", color: "#d9ff4f" },
  { number: "02", title: "Make every answer count", copy: "Bring responses together in one calm workspace, with the patterns and details you need in view.", color: "#c9b8ff" },
  { number: "03", title: "Create your own signal", copy: "Shape the look, pace, and personality of every form around the people you want to hear from.", color: "#ffb6d9" },
];

export default function Home() {
  return <main className="overflow-hidden bg-[#f7f6f2] text-[#171719]">
    <nav className="mx-auto flex max-w-[1400px] items-center justify-between px-6 py-6 lg:px-12">
      <Link href="/" className="text-2xl font-black tracking-[-0.08em]">typeform<span className="text-[#635bff]">.</span></Link>
      <div className="hidden items-center gap-8 text-sm font-medium lg:flex"><a href="#product" className="hover:text-[#635bff]">Product</a><a href="#why" className="hover:text-[#635bff]">Why us</a><a href="#stories" className="hover:text-[#635bff]">Stories</a><a href="#pricing" className="hover:text-[#635bff]">Pricing</a></div>
      <div className="flex items-center gap-3"><Link href="/forms" className="hidden rounded-full px-4 py-2 text-sm font-semibold hover:bg-white sm:inline-block">Log in</Link><Link href="/forms" className="rounded-full bg-[#635bff] px-5 py-3 text-sm font-semibold text-white transition hover:-translate-y-0.5 hover:bg-[#5148e8]">Get started <span className="ml-1">↗</span></Link></div>
    </nav>

    <section className="relative mx-auto max-w-[1400px] px-6 pb-20 pt-16 lg:px-12 lg:pb-28 lg:pt-24">
      <div className="pointer-events-none absolute -right-32 top-10 h-80 w-80 rounded-full bg-[#d9ff4f] blur-[1px] lg:h-[30rem] lg:w-[30rem]" />
      <div className="relative grid items-center gap-14 lg:grid-cols-[1.02fr_0.98fr]">
        <div className="max-w-2xl"><p className="mb-7 inline-flex rounded-full border border-black/10 bg-white/70 px-4 py-2 text-xs font-bold uppercase tracking-[0.2em]">The people-friendly way to ask</p><h1 className="text-[clamp(3.6rem,8vw,7.5rem)] font-black leading-[0.86] tracking-[-0.085em]">Make space<br /><span className="text-[#635bff]">for good</span><br />questions.</h1><p className="mt-9 max-w-lg text-lg leading-8 text-black/60 lg:text-xl">Beautiful forms that feel like a conversation. Collect the answers that move your work forward.</p><div className="mt-9 flex flex-wrap items-center gap-4"><Link href="/forms" className="rounded-full bg-[#171719] px-7 py-4 text-sm font-bold text-white transition hover:-translate-y-1 hover:bg-[#635bff]">Create a form <span className="ml-2">→</span></Link><a href="#product" className="rounded-full border border-black/15 px-7 py-4 text-sm font-bold transition hover:bg-white">See how it works <span className="ml-2">↓</span></a></div></div>
        <div className="relative min-h-[27rem] lg:min-h-[38rem]"><div className="absolute right-2 top-6 h-72 w-72 rotate-6 rounded-[3rem] bg-[#ffb6d9] lg:right-12 lg:h-[30rem] lg:w-[30rem]" /><div className="absolute left-4 top-0 z-10 w-[min(100%,27rem)] -rotate-3 rounded-[2rem] bg-white p-5 shadow-[0_25px_70px_rgba(30,20,50,0.18)] lg:left-8 lg:top-10"><div className="mb-12 flex items-center justify-between"><span className="text-xs font-bold text-black/40">CUSTOMER FEEDBACK</span><span className="h-2 w-2 rounded-full bg-[#635bff]" /></div><p className="text-3xl font-bold leading-tight tracking-tight">What makes your day a little better?</p><div className="mt-12 border-b-2 border-black/15 pb-3 text-sm text-black/35">Type your answer here...</div><div className="mt-7 flex items-center justify-between"><span className="text-xs text-black/35">1 of 4</span><span className="grid h-10 w-10 place-items-center rounded-full bg-[#635bff] text-white">→</span></div></div><div className="absolute bottom-0 right-0 z-20 w-52 rotate-6 rounded-[1.5rem] bg-[#171719] p-5 text-white shadow-2xl lg:right-4 lg:w-60"><p className="text-4xl font-black tracking-tight">3.5×</p><p className="mt-2 text-sm leading-5 text-white/60">more signal from better conversations</p><div className="mt-6 h-1.5 rounded-full bg-white/20"><div className="h-full w-3/4 rounded-full bg-[#d9ff4f]" /></div></div></div>
      </div>
    </section>

    <section id="product" className="bg-[#171719] px-6 py-20 text-white lg:px-12 lg:py-28"><div className="mx-auto max-w-[1400px]"><div className="grid gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#d9ff4f]">A better way to learn</p><h2 className="mt-5 max-w-xl text-5xl font-black leading-[0.95] tracking-[-0.07em] lg:text-7xl">Forms that start conversations.</h2></div><p className="max-w-md text-lg leading-8 text-white/55">From feedback to signups, make every interaction feel considered. Less friction for people. More useful answers for you.</p></div><div className="mt-16 grid gap-4 md:grid-cols-3">{features.map((feature) => <div key={feature.number} className="rounded-[2rem] p-7 text-[#171719]" style={{ backgroundColor: feature.color }}><p className="text-sm font-bold">{feature.number}</p><h3 className="mt-20 text-2xl font-black tracking-tight">{feature.title}</h3><p className="mt-4 text-sm leading-6 text-black/65">{feature.copy}</p><div className="mt-8 text-2xl">↗</div></div>)}</div></div></section>

    <section id="why" className="mx-auto max-w-[1400px] px-6 py-20 lg:px-12 lg:py-28"><div className="grid gap-12 lg:grid-cols-2 lg:items-center"><div className="relative min-h-[27rem] rounded-[2.5rem] bg-[#c9b8ff] p-7"><div className="absolute left-12 top-12 h-40 w-40 rounded-full bg-[#ffb6d9]" /><div className="absolute bottom-10 right-10 h-52 w-52 rounded-[2rem] bg-[#d9ff4f]" /><div className="absolute left-1/2 top-1/2 w-[min(80%,25rem)] -translate-x-1/2 -translate-y-1/2 rounded-3xl bg-white p-6 shadow-xl"><div className="flex items-center justify-between text-xs font-bold text-black/35"><span>RESPONSE SUMMARY</span><span>THIS WEEK</span></div><div className="mt-8 flex items-end gap-2"><div className="h-20 flex-1 rounded-t-lg bg-[#635bff]" /><div className="h-32 flex-1 rounded-t-lg bg-[#635bff]" /><div className="h-24 flex-1 rounded-t-lg bg-[#635bff]" /><div className="h-44 flex-1 rounded-t-lg bg-[#171719]" /><div className="h-28 flex-1 rounded-t-lg bg-[#635bff]" /></div><div className="mt-5 flex justify-between text-xs text-black/35"><span>Mon</span><span>Fri</span></div></div></div><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#635bff]">Made for humans</p><h2 className="mt-5 text-5xl font-black leading-[0.95] tracking-[-0.07em] lg:text-7xl">The details are the difference.</h2><p className="mt-7 max-w-lg text-lg leading-8 text-black/55">Give people room to think. Give your team answers worth acting on. Every screen is designed to keep the conversation moving.</p><Link href="/forms" className="mt-9 inline-flex rounded-full bg-[#635bff] px-6 py-4 text-sm font-bold text-white hover:bg-[#5148e8]">Build your first form →</Link></div></div></section>

    <section id="stories" className="border-y border-black/10 bg-white px-6 py-20 lg:px-12 lg:py-28"><div className="mx-auto max-w-[1400px] text-center"><p className="text-sm font-bold uppercase tracking-[0.2em] text-[#635bff]">A little more human</p><h2 className="mx-auto mt-5 max-w-4xl text-5xl font-black leading-[0.95] tracking-[-0.07em] lg:text-7xl">Good questions create better work.</h2><div className="mx-auto mt-12 max-w-3xl rounded-[2rem] bg-[#f7f6f2] p-8 text-left lg:p-12"><p className="text-2xl font-bold leading-tight tracking-tight lg:text-4xl">“The best form is the one people don&apos;t mind filling out.”</p><div className="mt-8 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-full bg-[#d9ff4f] font-bold">TF</div><div><p className="text-sm font-bold">The Typeform approach</p><p className="text-sm text-black/45">Thoughtful by design</p></div></div></div></div></section>

    <section id="pricing" className="bg-[#d9ff4f] px-6 py-20 lg:px-12 lg:py-28"><div className="mx-auto flex max-w-[1400px] flex-col items-start justify-between gap-10 lg:flex-row lg:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.2em]">Ready when you are</p><h2 className="mt-5 max-w-3xl text-6xl font-black leading-[0.88] tracking-[-0.08em] lg:text-8xl">Ask<br />away.</h2></div><div className="max-w-sm"><p className="text-lg leading-7 text-black/65">Start with a blank canvas, a seeded example, or a question you already know you need answered.</p><Link href="/forms" className="mt-7 inline-flex rounded-full bg-[#171719] px-7 py-4 text-sm font-bold text-white hover:bg-[#635bff]">Get started for free ↗</Link></div></div></section>

    <footer className="bg-[#171719] px-6 py-10 text-white lg:px-12"><div className="mx-auto flex max-w-[1400px] flex-col justify-between gap-6 sm:flex-row sm:items-center"><Link href="/" className="text-2xl font-black tracking-[-0.08em]">typeform<span className="text-[#d9ff4f]">.</span></Link><div className="flex gap-6 text-sm text-white/55"><Link href="/forms" className="hover:text-white">Workspace</Link><a href="#product" className="hover:text-white">Product</a><a href="#why" className="hover:text-white">Why us</a></div><p className="text-sm text-white/35">Built for better questions.</p></div></footer>
  </main>;
}
